---

- name: Update apt-cache
  apt: update_cache=yes 

- name: install grpc dependencies
  apt: name={{ item }} state=latest
  with_items:
  - 'build-essential'
  - 'autoconf'
  - 'libtool'
  - 'pkg-config'
  - 'libgflags-dev'
  - 'libgtest-dev'
  - 'clang'
  - 'libc++-dev'

- name: determine latest release to install
  command: curl -L https://grpc.io/release
  register: latest_grpc_release

- name: check out grpc
  git: repo=https://github.com/grpc/grpc
    dest={{freeswitch_sources_path}}/libs/grpc
    version={{latest_grpc_release.stdout}}
    depth=50
    accept_hostkey=yes
    force=yes
      
- name: update submodules
  shell: git submodule update --init --recursive chdir={{freeswitch_sources_path}}/libs/grpc

- name: build grpc
  shell: make && make install chdir={{freeswitch_sources_path}}/libs/grpc

- name: check out googleapis
  git: repo=https://github.com/googleapis/googleapis
       dest={{freeswitch_sources_path}}/libs/googleapis
       version=master
       depth=50
       accept_hostkey=yes
       force=yes

- name: build googleapis
  shell: LANGUAGE=cpp make chdir={{freeswitch_sources_path}}/libs/googleapis

- name: patch configure.ac
  patch:
    src: configure.ac.patch
    dest: "{{freeswitch_sources_path}}/configure.ac"

- name: patch Makefile.am
  patch:
    src: Makefile.am.patch
    dest: "{{freeswitch_sources_path}}/Makefile.am"

- name: re-run Freeswitch configuration
  shell: ./{{freeswitch_configure_command}} chdir={{freeswitch_sources_path}}

- name: re-run FreeSwitch make
  shell: make chdir={{freeswitch_sources_path}}

- name: re-run FreeSwitch install
  shell: make install chdir={{freeswitch_sources_path}}

