---

- name: copy modules into place
  shell: cp -r -n "{{ item.src }}" "{{ item.dest }}"
  args:
    warn: False
  loop:
    - {src: /usr/local/src/drachtio-freeswitch-modules/modules/mod_google_transcribe/, dest: "{{freeswitch_sources_path}}/src/mod/applications/"}
    - {src: /usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/, dest: "{{freeswitch_sources_path}}/src/mod/applications/"}
    - {src: /usr/local/src/drachtio-freeswitch-modules/modules/mod_dialogflow/, dest: "{{freeswitch_sources_path}}/src/mod/applications/"}
    - {src: /usr/local/src/drachtio-freeswitch-modules/modules/mod_aws_transcribe/, dest: "{{freeswitch_sources_path}}/src/mod/applications/"}

- name: copy files for grpc and aws transcribe
  copy:
    remote_src: no
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: "configure.ac.extra", dest: "{{freeswitch_sources_path}}/configure.ac"}
    - {src: "Makefile.am.extra", dest: "{{freeswitch_sources_path}}/Makefile.am"}
    - {src: "modules.conf.in.extra", dest: "{{freeswitch_sources_path}}/build/modules.conf.in"}

- name: copy vanilla conf
  copy:
    src: modules.conf.vanilla.xml.extra
    dest: "{{freeswitch_sources_path}}/conf/vanilla/autoload_configs/modules.conf.xml"

- name: check out aws-sdk-cpp
  git:
    repo: https://github.com/aws/aws-sdk-cpp.git
    dest: "{{freeswitch_sources_path}}/libs/aws-sdk-cpp"
    version: "{{aws_sdk_version}}"
    depth: 50
    accept_hostkey: yes
    force: yes

- name: build aws-sdk-cpp
  shell: |
    mkdir -p build && cd build
    cmake .. -DBUILD_ONLY=transcribestreaming -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_SHARED_LIBS=OFF
    make
  args:
    chdir: "{{freeswitch_sources_path}}/libs/aws-sdk-cpp"

#- name: determine latest release to install
#  command: curl -L https://grpc.io/release
#  args:
#    warn: false
#  register: latest_grpc_release

- name: check out grpc
  git: repo=https://github.com/grpc/grpc
    dest=/usr/local/src/grpc
    version={{grpc_version}}
    depth=50
    accept_hostkey=yes
    force=yes
            
- name: update submodules
  shell: git submodule update --init --recursive
  args:
    chdir: /usr/local/src/grpc

- name: build grpc protobuf
  shell: ./autogen.sh && ./configure && make install 
  args:
    chdir: /usr/local/src/grpc/third_party/protobuf

- name: build grpc
  shell: export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && make && make install 
  args:
    chdir: /usr/local/src/grpc

- name: check out googleapis
  git: repo=https://github.com/davehorton/googleapis
       dest={{freeswitch_sources_path}}/libs/googleapis
       version=dialogflow-v2-support
       accept_hostkey=yes
       force=yes

- name: build googleapis
  shell: LANGUAGE=cpp make chdir={{freeswitch_sources_path}}/libs/googleapis

